### PR TITLE
Fix/qkm 215

### LINKED ISSUE #215: Fix error handling
Since the implementation of Connectors, the error handling is wrong because we do not log where the error happens. This means that we return an internal error to the users instead of logging it and mapping it to a suitable error message. All stores are affected.

### PR DESCRIPTION
**Pull request by darioAnongba**
## Fixed Issue(s)
fixes #215 by rewriting the error handling + some bugs in the connectors

### CODE REVIEW

File: src/stores/store/keys/keys.go [hunk 1]
```diff
@@ -70,7 +70,7 @@ func VerifySignature(logger log.Logger, pubKey, data, sig []byte, algo *entities
 	case algo.EllipticCurve == entities.Bn254 && algo.Type == entities.Eddsa:
 		verified, err = crypto.VerifyEDDSASignature(pubKey, data, sig)
 	default:
-		errMessage := "unsupported algorithm"
+		errMessage := "unsupported signing algorithm and "
```
Comment (6l20) [inline src/stores/store/keys/keys.go:73]: Is end of message missing ?

**Review by 6l20 — APPROVED** [review]
One minor comment.

File: src/stores/store/keys/keys.go (hunk 1 above)
Comment (darioAnongba) [reply src/stores/store/keys/keys.go:73]: good catch, fixed.
